version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile-prod
    depends_on:
      - db
    command:
      [
        './wait-for-it.sh',
        'db:5432',
        '--',
        'bash',
        '-c',
        'cd server && npm run deploy',
      ]
    ports:
      - 80:80
    working_dir: '/usr/src/app'
    restart: always
    environment:
      - NODE_ENV=production
      - SERVER_PORT=80
      - TZ=Asia/Seoul
  db:
    image: postgres:13.3
    expose:
      - '5432'
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - TZ=Asia/Seoul
    volumes:
      - ./db:/var/lib/postgresql/data
